### PR TITLE
support running in GitPod

### PR DESCRIPTION
**Pull request by philschatz**
This adds support for editing and rebuilding styles directly in GitPod.

Unfortunately it seems this repo uses an old version of Dart and upgrading to version 3 requires some migration... so there is a little extra code in here which installs the old version (`dart@2.19`) and links it to be `dart`

### CODE REVIEW

**Comment by LostMojo** [comment]
Looks like the sass.dart & dart source maps might need updating as well-- build-styles is failing.

**Review by LostMojo — CHANGES_REQUESTED** [review]
Unfortunately, it looks like the changes made to dart are throwing a wrench into our build.dart script-- importing sass.dart and source_maps.dart aren't working at all in the script. 

Depending on how high priority gitpod is, we can either prioritize an upgrade to dart or wait until Kendra finalizes something with Stylish (an upgrade/language change for the ce-styles repo)

**Comment by philschatz** [comment]
I added the `.dart_tool/` files back. Hopefully that works!

**Review by LostMojo — APPROVED** [review]
All styles are building without changes! Good job, Phil!!!

**Comment by philschatz** [comment]
Test instructions:

1. Open this repo in GitPod (clicking the link on the page is probably the easiest. see screenshot)
2. Once VSCode opens up, in the Terminal panel type `./script/build-styles`

image

**Pull request merged**
