### PR TITLE
Add overflow:auto to webview figures

### PR DESCRIPTION
**Pull request by RoyEJohnson**
For: https://github.com/openstax/unified/issues/2673

### CODE REVIEW

**Review by kswanson33 — APPROVED** [review]

**Comment by kswanson33** [comment]
btw @RoyEJohnson -- what's needed to test this? i'll send to @Stackblocks before merge

**Comment by RoyEJohnson** [comment]
The issue is that some pages ([example](https://rex-web-production.herokuapp.com/books/workplace-software-skills@c795d5f/pages/preface?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20231109.173216)) in Rex have images down the page that have large `width` values, which causes the main content section to be horizontally-scrollable.
When you scroll down to them, they lazy-load, and once loaded, they are constrained to the normal page area. It's a weird artifact of the images not being loaded.
The test is that the page loads and is not horizontally-scrollable, and also that nothing looks weird about the images (like, they shouldn't have scroll bars).

**Comment by lwtchu** [comment]
@RoyEJohnson -- this has been tested and ready to merge

**Comment by lwtchu** [comment]
@RoyEJohnson yelling disregard kendra beat me to it

**Pull request merged**
